// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnalyzeScript() {
  return window['go']['main']['App']['AnalyzeScript']();
}

export function ApplyUpdate() {
  return window['go']['main']['App']['ApplyUpdate']();
}

export function AutoDetectROI(arg1, arg2) {
  return window['go']['main']['App']['AutoDetectROI'](arg1, arg2);
}

export function CheckAIRoiAvailable() {
  return window['go']['main']['App']['CheckAIRoiAvailable']();
}

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function CheckGeneratorDependencies() {
  return window['go']['main']['App']['CheckGeneratorDependencies']();
}

export function ClearCache() {
  return window['go']['main']['App']['ClearCache']();
}

export function ConnectDevice(arg1) {
  return window['go']['main']['App']['ConnectDevice'](arg1);
}

export function ConnectDeviceVia(arg1, arg2) {
  return window['go']['main']['App']['ConnectDeviceVia'](arg1, arg2);
}

export function CurrentVersion() {
  return window['go']['main']['App']['CurrentVersion']();
}

export function DisconnectDevice() {
  return window['go']['main']['App']['DisconnectDevice']();
}

export function GenerateScript(arg1) {
  return window['go']['main']['App']['GenerateScript'](arg1);
}

export function GetCacheInfo() {
  return window['go']['main']['App']['GetCacheInfo']();
}

export function GetDeviceStatus() {
  return window['go']['main']['App']['GetDeviceStatus']();
}

export function GetHardwareInfo() {
  return window['go']['main']['App']['GetHardwareInfo']();
}

export function GetHeatmap(arg1) {
  return window['go']['main']['App']['GetHeatmap'](arg1);
}

export function GetMarker(arg1) {
  return window['go']['main']['App']['GetMarker'](arg1);
}

export function GetOMarkers(arg1) {
  return window['go']['main']['App']['GetOMarkers'](arg1);
}

export function GetScriptActions() {
  return window['go']['main']['App']['GetScriptActions']();
}

export function GetScriptCurve(arg1) {
  return window['go']['main']['App']['GetScriptCurve'](arg1);
}

export function GetScriptOffset() {
  return window['go']['main']['App']['GetScriptOffset']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function LabelScene(arg1, arg2) {
  return window['go']['main']['App']['LabelScene'](arg1, arg2);
}

export function LoadFirstFrame(arg1) {
  return window['go']['main']['App']['LoadFirstFrame'](arg1);
}

export function LoadFunscript(arg1) {
  return window['go']['main']['App']['LoadFunscript'](arg1);
}

export function OpenLogFolder() {
  return window['go']['main']['App']['OpenLogFolder']();
}

export function PickFunscriptFile() {
  return window['go']['main']['App']['PickFunscriptFile']();
}

export function PickReportPath() {
  return window['go']['main']['App']['PickReportPath']();
}

export function PickVideoFile() {
  return window['go']['main']['App']['PickVideoFile']();
}

export function QualityModelInfo() {
  return window['go']['main']['App']['QualityModelInfo']();
}

export function ReportArousal(arg1) {
  return window['go']['main']['App']['ReportArousal'](arg1);
}

export function ReportExists() {
  return window['go']['main']['App']['ReportExists']();
}

export function ReportSummary() {
  return window['go']['main']['App']['ReportSummary']();
}

export function ReportVideoPosition(arg1) {
  return window['go']['main']['App']['ReportVideoPosition'](arg1);
}

export function SaveMarker(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveMarker'](arg1, arg2, arg3);
}

export function SaveOMarkers(arg1, arg2) {
  return window['go']['main']['App']['SaveOMarkers'](arg1, arg2);
}

export function SaveScriptActions(arg1) {
  return window['go']['main']['App']['SaveScriptActions'](arg1);
}

export function ScriptExistsForVideo(arg1) {
  return window['go']['main']['App']['ScriptExistsForVideo'](arg1);
}

export function SetScriptOffset(arg1) {
  return window['go']['main']['App']['SetScriptOffset'](arg1);
}

export function SetSetting(arg1, arg2) {
  return window['go']['main']['App']['SetSetting'](arg1, arg2);
}

export function StartPlayback(arg1) {
  return window['go']['main']['App']['StartPlayback'](arg1);
}

export function StartTraining(arg1) {
  return window['go']['main']['App']['StartTraining'](arg1);
}

export function StopPlayback() {
  return window['go']['main']['App']['StopPlayback']();
}

export function StopTraining() {
  return window['go']['main']['App']['StopTraining']();
}

export function StopTrainingCycle() {
  return window['go']['main']['App']['StopTrainingCycle']();
}

export function SubmitFeedback(arg1) {
  return window['go']['main']['App']['SubmitFeedback'](arg1);
}

export function SuggestProfile(arg1) {
  return window['go']['main']['App']['SuggestProfile'](arg1);
}

export function TestRawValue(arg1, arg2) {
  return window['go']['main']['App']['TestRawValue'](arg1, arg2);
}

export function TestStop() {
  return window['go']['main']['App']['TestStop']();
}

export function TestSuction(arg1) {
  return window['go']['main']['App']['TestSuction'](arg1);
}

export function TestVibration(arg1) {
  return window['go']['main']['App']['TestVibration'](arg1);
}

export function TrainQualityModel() {
  return window['go']['main']['App']['TrainQualityModel']();
}

export function TriggerExtendedO(arg1, arg2, arg3) {
  return window['go']['main']['App']['TriggerExtendedO'](arg1, arg2, arg3);
}

export function VideoFileURL() {
  return window['go']['main']['App']['VideoFileURL']();
}
