// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {generator} from '../models';
import {funscript} from '../models';
import {motionx} from '../models';

export function AnalyzeScript():Promise<main.ScriptAnalysis>;

export function ApplyRingDown(arg1:number,arg2:number):Promise<void>;

export function ApplySuggestedOZone():Promise<funscript.OZoneSuggestion>;

export function ApplyUpdate():Promise<void>;

export function AutoDetectROI(arg1:string,arg2:string):Promise<void>;

export function BootstrapRoiTrainingSample(arg1:string,arg2:generator.ROI|null,arg3:generator.ROI|null,arg4:string,arg5:string):Promise<string>;

export function CheckAIRoiAvailable():Promise<boolean>;

export function CheckAudioCheckAvailable():Promise<boolean>;

export function CheckForUpdate():Promise<main.UpdateCheckResult>;

export function CheckGeneratorDependencies():Promise<void>;

export function ClearCache():Promise<main.CacheInfo>;

export function ConnectDevice(arg1:boolean):Promise<main.DeviceStatus>;

export function ConnectDeviceVia(arg1:string,arg2:string):Promise<main.DeviceStatus>;

export function CurrentVersion():Promise<string>;

export function DiscardRoiTrainingSample(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DisconnectDevice():Promise<main.DeviceStatus>;

export function GenerateScript(arg1:main.GenerateOptions):Promise<void>;

export function GetBenchmarkHistory():Promise<Array<generator.BenchmarkResult>>;

export function GetCacheInfo():Promise<main.CacheInfo>;

export function GetDeviceStatus():Promise<main.DeviceStatus>;

export function GetDiagnosticsHistory():Promise<Array<main.DiagnosticsHistoryEntry>>;

export function GetHardwareInfo():Promise<string>;

export function GetHeatmap(arg1:number):Promise<Array<main.HeatmapPoint>>;

export function GetMarker(arg1:string):Promise<main.Marker>;

export function GetOMarkers(arg1:string):Promise<Array<funscript.OMarker>>;

export function GetRoiDatasetSummary(arg1:string):Promise<main.RoiDatasetSummary>;

export function GetRoiTrainingSampleImage(arg1:string):Promise<string>;

export function GetScriptActions():Promise<Array<funscript.Action>>;

export function GetScriptCurve(arg1:number):Promise<Array<main.CurvePoint>>;

export function GetScriptOffset():Promise<number>;

export function GetSettings():Promise<main.Settings>;

export function InvertLoadedScript():Promise<void>;

export function InvertScriptAtPath(arg1:string):Promise<void>;

export function LabelScene(arg1:string,arg2:string):Promise<void>;

export function ListRoiTrainingSamples(arg1:string,arg2:string):Promise<Array<main.RoiTrainingSample>>;

export function LoadFirstFrame(arg1:string):Promise<main.FramePreview>;

export function LoadFunscript(arg1:string):Promise<main.ScriptInfo>;

export function OpenLogFolder():Promise<void>;

export function PickBenchmarkManifest():Promise<string>;

export function PickFunscriptFile():Promise<string>;

export function PickReportPath():Promise<string>;

export function PickVideoFile():Promise<string>;

export function QualityModelInfo():Promise<string>;

export function ReportArousal(arg1:number):Promise<void>;

export function ReportExists():Promise<boolean>;

export function ReportSummary():Promise<string>;

export function ReportVideoPosition(arg1:number):Promise<void>;

export function ReviewGeneratedScript(arg1:string):Promise<main.GeneratedReview>;

export function RunDeviceDiagnostics():Promise<void>;

export function RunGoldenClipBenchmark(arg1:string):Promise<void>;

export function RunRoiModelTraining(arg1:number,arg2:string):Promise<void>;

export function SaveMarker(arg1:string,arg2:number,arg3:number):Promise<void>;

export function SaveOMarkers(arg1:string,arg2:Array<funscript.OMarker>):Promise<void>;

export function SaveScriptActions(arg1:Array<funscript.Action>):Promise<void>;

export function ScriptChapters():Promise<Array<motionx.Chapter>>;

export function ScriptExistsForVideo(arg1:string):Promise<boolean>;

export function ScriptQuality():Promise<generator.ScriptQualityResult>;

export function SetScriptOffset(arg1:number):Promise<void>;

export function SetSetting(arg1:string,arg2:any):Promise<void>;

export function StartPlayback(arg1:main.PlaybackOptions):Promise<void>;

export function StartTraining(arg1:main.TrainingRequest):Promise<void>;

export function StopPlayback():Promise<void>;

export function StopTraining():Promise<void>;

export function StopTrainingCycle():Promise<void>;

export function SubmitFeedback(arg1:main.ReportFeedback):Promise<void>;

export function SuggestBackend(arg1:number,arg2:number):Promise<string>;

export function SuggestOZone():Promise<funscript.OZoneSuggestion>;

export function SuggestPolarity():Promise<funscript.PolarityHint>;

export function SuggestProfile(arg1:string):Promise<generator.ProfileSuggestion>;

export function TestRawValue(arg1:string,arg2:number):Promise<void>;

export function TestStop():Promise<void>;

export function TestSuction(arg1:number):Promise<void>;

export function TestVibration(arg1:number):Promise<void>;

export function TrainQualityModel():Promise<string>;

export function TrainingHistory():Promise<Array<main.TrainingSessionSummary>>;

export function TriggerExtendedO(arg1:number,arg2:number,arg3:number):Promise<void>;

export function UpdateRoiTrainingSample(arg1:string,arg2:string,arg3:string,arg4:Array<main.RoiTrainingBox>):Promise<void>;

export function VideoFileURL():Promise<string>;
